# Dear emacs, this is -*- makefile -*-
# Andre Rabello <Andre.dos.Anjos@cern.ch>

sinclude ../config.mk
DEPEND = sys
CXXFLAGS += -DHAVE_INLINE
LDFLAGS += 
INSTALL_DIR=../$(INSTALL_NAME)
sinclude ../build.mk
